#define DEFS_SELCAMPUSKEY       @"SelectedCampus"
#define DEFS_LASTVIEWEDDEPART   @"LastViewedDepart"
#define DEFS_LASTSPORTSUPDATE   @"LastSportsUpdate"
#define DEFS_PARKINGPERMIT      @"ParkingPermit"
#define DEFS_LASTVIEWEDSEM      @"LastViewedSemester"
#define CAMPUSDICTNAME          @"availableCampuses.txt"
#define ABBRSDICTNAME           @"sportsAbbrsDict.txt"